---
- name: Ensure firewall package is installed
  hosts: all # Replace with specific host(s) or group
  become: true
  tasks:
    - name: Check if firewalld is installed
      ansible.builtin.stat:
        path: /usr/sbin/firewalld
      register: firewalld_check

    - name: Firewall package already installed
      debug:
        msg: "Firewalld package already present"
      when: firewalld_check.stat.exists
