---
- name: Ensure firewall package is installed
  hosts: all # Replace with specific host(s) or group
  become: true

  tasks:
    - name: Install firewalld package if not found
      ansible.builtin.dnf:
        name: firewalld
        state: present
      when: not firewalld_check.stat.exists
