---
- name: Ensure firewall package is installed
  hosts: 192.168.101.21
  become: true
  tasks:
    - name: Install firewalld package if not found
      ansible.builtin.dnf:
        name: firewalld
        state: present
      when: not firewalld_check.stat.exists
