---
- name: 12th Temp
  hosts: 192.168.101.21
  tasks:
    - name: Add a basic audit config
      ansible.builtin.copy:
        src: audit.rules
        dest: /etc/audit/rules.d/audit.rules
        owner: root
        group: root
        mode: 0600
      notify: reboot_host
    handlers:
      - name: reboot_host
        ansible.builtin.reboot:
          reboot_timeout: 360
