---
- name: 2nd Temp
  hosts: 192.168.101.21
  tasks: 
    - name: Ensure firewall service is up and running
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes
