---
- name: 7th Temp
  hosts: 192.168.101.21
  tasks: 
    - name: Harden network parameters
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: '{{ item.value }}'
        sysctl_set: yes
        state: present
        reload: yes
        sysctl_file: /etc/sysctl.d/90-net.conf
      loop:
      - name: net.ipv4.tcp_syncookies
        value: 1
      - name: net.ipv4.conf.default.log_martians
        value: 1
      - name: net.ipv4.conf.all.log_martians
        value: 1
      - name: net.ipv4.conf.all.accept_source_route
        value: 0
      - name: net.ipv4.conf.default.accept_source_route
        value: 0
      - name: net.ipv6.conf.all.accept_source_route
        value: 0
      - name: net.ipv6.conf.default.accept_source_route
        value: 0
